import { Translations } from "../types";
export const ar: Translations = {
  nav: { features: "الميزات", liveDemo: "عرض مباشر", howItWorks: "كيف يعمل", github: "GitHub", tryDemo: "جرب العرض" },
  hero: { badge: "مدعوم من Murf Falcon — ~130 مللي ثانية تأخير", titleLine1: "ذكاؤك", titleLine2: "المحفز", titleLine3: "على Discord", subtitle: "بوت Discord ينضم إلى قناتك الصوتية كمعلق مباشر أو مدرب إنتاجية أو مراجع كود لاذع — كل ذلك بصوت في الوقت الفعلي.", ctaTryDemo: "جرب العرض المباشر", ctaAddDiscord: "أضف إلى Discord", botName: "HypeBot", botStatus: "● متصل في الصوت", botQuote: '"يا! آخر commit كان ناري 🔥 إعادة هيكلة نظيفة، أنواع صحيحة، صفر تحذيرات. أنت مختلف اليوم!"' },
  features: { label: "الميزات", title: "مبني لـ", titleHighlight: "الوقت الفعلي", subtitle: "كل ما تحتاجه لزميل ذكاء اصطناعي يتحدث إليك فعلاً على Discord.", items: [{ title: "صوت في الوقت الفعلي", description: "ينضم إلى قناتك الصوتية على Discord ويرد فوراً باستخدام TTS فائق السرعة من Murf Falcon." }, { title: "~130 مللي ثانية استجابة", description: "استدلال Falcon فائق السرعة يعني تدفق محادثة طبيعي بدون انقطاع." }, { title: "تعليقات GitHub", description: "اربط webhooks واحصل على إعلانات صوتية مباشرة تمدح أو تنتقد commits." }, { title: "شخصيات متعددة", description: "بدّل بين المحفز والمدرب الصارم ومراجع الكود أو أنشئ شخصيتك الخاصة." }, { title: "تحويل الكلام لنص", description: "يستمع لصوتك في الوقت الفعلي، يفهم السياق، ويرد بذكاء." }, { title: "أوضاع الإنتاجية", description: "إعلانات مؤقت بومودورو، تذكيرات الاجتماعات اليومية، وتدريب جلسات التركيز." }] },
  howItWorks: { label: "كيف يعمل", title: "جاهز للعمل في ", titleHighlight: "دقائق", steps: [{ title: "ادعُ HypeBot", description: "أضف HypeBot إلى خادم Discord بنقرة واحدة. امنح أذونات القناة الصوتية." }, { title: "انضم لقناة صوتية", description: "HypeBot يكتشف وجودك في قناة صوتية وينضم تلقائياً (أو بأمر)." }, { title: "ابدأ بالتحدث", description: "تحدث بشكل طبيعي. HypeBot يستمع عبر STT، يعالج بالذكاء الاصطناعي، ويرد بـ Murf Falcon TTS في ~130 مللي ثانية." }, { title: "اربط GitHub", description: "اختياري: اربط مستودعاتك. HypeBot يعلن عن commits و PRs ونتائج CI مباشرة بالصوت." }] },
  demo: { label: "عرض مباشر", title: "تحدث مع ", titleHighlight: "HypeBot", subtitle: "انقر على الميكروفون، قل شيئاً واسمع زميلك الذكي يرد بصوت Murf Falcon فائق السرعة.", personas: { hype: "🔥 المحفز", coach: "🎯 المدرب الصارم", roast: "💀 ناقد الكود" }, voiceLabel: "🦅 أصوات Murf Falcon", loadingVoices: "تحميل الأصوات...", selectVoice: "اختر صوت Falcon", noVoices: "لم يتم العثور على أصوات Falcon. تحقق من مفتاح API.", clickMic: "انقر على الميكروفون وتحدث", listening: "جارٍ الاستماع... انقر للإيقاف", processing: "المعالجة مع Falcon AI...", speaking: "HypeBot يتحدث عبر Murf Falcon...", youSaid: "قلت:", loadingFalcon: "تحميل أصوات Falcon..." },
  footer: { builtWith: "مبني بـ Murf Falcon • Hackathon 2026" },
  languageSwitcher: { search: "ابحث عن اللغات...", noResults: "لم يتم العثور على لغات" },
};
