import { Translations } from "../types";
export const de: Translations = {
  nav: { features: "Funktionen", liveDemo: "Live-Demo", howItWorks: "So funktioniert's", github: "GitHub", tryDemo: "Demo testen" },
  hero: { badge: "Angetrieben von Murf Falcon — ~130ms Latenz", titleLine1: "Dein KI", titleLine2: "Hype Man", titleLine3: "auf Discord", subtitle: "Ein Discord-Bot, der deinem Sprachkanal als Live-Kommentator, Produktivitäts-Coach oder gnadenloser Code-Reviewer beitritt — alles in Echtzeit-Stimme.", ctaTryDemo: "Live-Demo testen", ctaAddDiscord: "Zu Discord hinzufügen", botName: "HypeBot", botStatus: "● Online im Sprachkanal", botQuote: '"Yo! Der letzte Commit war FEUER 🔥 Sauberes Refactoring, korrekte Typen, null Warnungen. Du bist heute anders drauf!"' },
  features: { label: "Funktionen", title: "Gebaut für ", titleHighlight: "Echtzeit", subtitle: "Alles was du brauchst für einen KI-Kollegen, der wirklich mit dir auf Discord spricht.", items: [{ title: "Echtzeit-Stimme", description: "Tritt deinem Discord-Sprachkanal bei und antwortet sofort mit Murf Falcons ultra-niedrige Latenz TTS." }, { title: "~130ms Antwort", description: "Falcons blitzschnelle Inferenz ermöglicht natürlichen, ununterbrochenen Gesprächsfluss." }, { title: "GitHub-Roasts", description: "Verbinde Webhooks und erhalte Live-Sprachansagen, die deine Commits loben oder rösten." }, { title: "Mehrere Persönlichkeiten", description: "Wechsle zwischen Hype Man, Strenger Coach, Code-Reviewer oder erstelle deine eigene Persönlichkeit." }, { title: "Sprache-zu-Text", description: "Hört deiner Stimme in Echtzeit zu, versteht den Kontext und antwortet intelligent." }, { title: "Produktivitätsmodi", description: "Pomodoro-Timer-Ansagen, Standup-Erinnerungen und Fokus-Session-Coaching." }] },
  howItWorks: { label: "So funktioniert's", title: "Einsatzbereit in ", titleHighlight: "Minuten", steps: [{ title: "HypeBot einladen", description: "Füge HypeBot mit einem Klick zu deinem Discord-Server hinzu. Gewähre Sprachkanal-Berechtigungen." }, { title: "Sprachkanal beitreten", description: "HypeBot erkennt, wenn du in einem Sprachkanal bist und tritt automatisch bei (oder auf Befehl)." }, { title: "Anfangen zu sprechen", description: "Sprich natürlich. HypeBot hört via STT zu, verarbeitet mit KI und antwortet mit Murf Falcon TTS in ~130ms." }, { title: "GitHub verbinden", description: "Optional: Verknüpfe deine Repos. HypeBot kündigt Commits, PRs und CI-Ergebnisse live per Sprache an." }] },
  demo: { label: "Live-Demo", title: "Sprich mit ", titleHighlight: "HypeBot", subtitle: "Klicke auf das Mikrofon, sage etwas und höre deinen KI-Kollegen mit Murf Falcons ultra-niedriger Latenz antworten.", personas: { hype: "🔥 Hype Man", coach: "🎯 Strenger Coach", roast: "💀 Code-Röster" }, voiceLabel: "🦅 Murf Falcon Stimmen", loadingVoices: "Stimmen laden...", selectVoice: "Falcon-Stimme wählen", noVoices: "Keine Falcon-Stimmen gefunden. API-Schlüssel prüfen.", clickMic: "Klicke auf das Mikrofon und sprich", listening: "Höre zu... klicke zum Stoppen", processing: "Verarbeitung mit Falcon AI...", speaking: "HypeBot spricht via Murf Falcon...", youSaid: "Du hast gesagt:", loadingFalcon: "Falcon-Stimmen laden..." },
  footer: { builtWith: "Erstellt mit Murf Falcon • Hackathon 2026" },
  languageSwitcher: { search: "Sprachen suchen...", noResults: "Keine Sprachen gefunden" },
};
