import { Translations } from "../types";
export const es: Translations = {
  nav: { features: "Características", liveDemo: "Demo en vivo", howItWorks: "Cómo funciona", github: "GitHub", tryDemo: "Probar demo" },
  hero: { badge: "Impulsado por Murf Falcon — ~130ms de latencia", titleLine1: "Tu IA", titleLine2: "Animador", titleLine3: "en Discord", subtitle: "Un bot de Discord que se une a tu canal de voz como comentarista en vivo, coach de productividad o revisor de código despiadado — todo en voz en tiempo real.", ctaTryDemo: "Probar demo en vivo", ctaAddDiscord: "Agregar a Discord", botName: "HypeBot", botStatus: "● En línea en voz", botQuote: '"¡Oye! ¡Ese último commit fue FUEGO 🔥 Refactorización limpia, tipos correctos, cero advertencias. ¡Hoy eres diferente!"' },
  features: { label: "Características", title: "Construido para ", titleHighlight: "tiempo real", subtitle: "Todo lo que necesitas para un compañero de IA que realmente te habla en Discord.", items: [{ title: "Voz en tiempo real", description: "Se une a tu canal de voz de Discord y responde instantáneamente usando el TTS de ultra baja latencia de Murf Falcon." }, { title: "~130ms de respuesta", description: "La inferencia ultrarrápida de Falcon permite un flujo de conversación natural e ininterrumpido." }, { title: "Roasts de GitHub", description: "Conecta webhooks y recibe anuncios de voz en vivo alabando o criticando tus commits." }, { title: "Múltiples personas", description: "Cambia entre Animador, Coach Estricto, Revisor de Código o crea tu propia personalidad." }, { title: "Voz a texto", description: "Escucha tu voz en tiempo real, entiende el contexto y responde inteligentemente." }, { title: "Modos de productividad", description: "Anuncios de temporizador Pomodoro, recordatorios de standup y coaching de sesiones de enfoque." }] },
  howItWorks: { label: "Cómo funciona", title: "Listo y funcionando en ", titleHighlight: "minutos", steps: [{ title: "Invita a HypeBot", description: "Agrega HypeBot a tu servidor de Discord con un clic. Otorga permisos de canal de voz." }, { title: "Únete a un canal de voz", description: "HypeBot detecta cuando estás en un canal de voz y se une automáticamente (o por comando)." }, { title: "Empieza a hablar", description: "Habla naturalmente. HypeBot escucha vía STT, procesa con IA y responde con Murf Falcon TTS en ~130ms." }, { title: "Conecta GitHub", description: "Opcional: Vincula tus repos. HypeBot anuncia commits, PRs y resultados de CI en vivo por voz." }] },
  demo: { label: "Demo en vivo", title: "Habla con ", titleHighlight: "HypeBot", subtitle: "Haz clic en el micrófono, di algo y escucha a tu compañero de IA responder con la voz de ultra baja latencia de Murf Falcon.", personas: { hype: "🔥 Animador", coach: "🎯 Coach Estricto", roast: "💀 Crítico de código" }, voiceLabel: "🦅 Voces Murf Falcon", loadingVoices: "Cargando voces...", selectVoice: "Seleccionar voz Falcon", noVoices: "No se encontraron voces Falcon. Verifica tu clave API.", clickMic: "Haz clic en el micrófono y habla", listening: "Escuchando... haz clic para detener", processing: "Procesando con Falcon AI...", speaking: "HypeBot está hablando vía Murf Falcon...", youSaid: "Dijiste:", loadingFalcon: "Cargando voces Falcon..." },
  footer: { builtWith: "Construido con Murf Falcon • Hackathon 2026" },
  languageSwitcher: { search: "Buscar idiomas...", noResults: "No se encontraron idiomas" },
};
