import { Translations } from "../types";
export const fr: Translations = {
  nav: { features: "Fonctionnalités", liveDemo: "Démo en direct", howItWorks: "Comment ça marche", github: "GitHub", tryDemo: "Essayer la démo" },
  hero: { badge: "Propulsé par Murf Falcon — ~130ms de latence", titleLine1: "Votre IA", titleLine2: "Hype Man", titleLine3: "sur Discord", subtitle: "Un bot Discord qui rejoint votre canal vocal en tant que commentateur en direct, coach de productivité ou critique de code impitoyable — le tout en voix temps réel.", ctaTryDemo: "Essayer la démo", ctaAddDiscord: "Ajouter à Discord", botName: "HypeBot", botStatus: "● En ligne en vocal", botQuote: '"Yo ! Ce dernier commit était du FEU 🔥 Refactoring propre, types corrects, zéro warning. Tu es au top aujourd\'hui !"' },
  features: { label: "Fonctionnalités", title: "Conçu pour le ", titleHighlight: "temps réel", subtitle: "Tout ce dont vous avez besoin pour un collègue IA qui vous parle vraiment sur Discord.", items: [{ title: "Voix en temps réel", description: "Rejoint votre canal vocal Discord et répond instantanément grâce au TTS ultra-faible latence de Murf Falcon." }, { title: "~130ms de réponse", description: "L'inférence ultra-rapide de Falcon permet un flux de conversation naturel et ininterrompu." }, { title: "Roasts GitHub", description: "Connectez des webhooks et recevez des annonces vocales en direct louant ou critiquant vos commits." }, { title: "Personnalités multiples", description: "Basculez entre Hype Man, Coach Strict, Critique de Code ou créez votre propre personnalité." }, { title: "Reconnaissance vocale", description: "Écoute votre voix en temps réel, comprend le contexte et répond intelligemment." }, { title: "Modes productivité", description: "Annonces minuteur Pomodoro, rappels de standup et coaching de sessions de concentration." }] },
  howItWorks: { label: "Comment ça marche", title: "Opérationnel en ", titleHighlight: "minutes", steps: [{ title: "Invitez HypeBot", description: "Ajoutez HypeBot à votre serveur Discord en un clic. Accordez les permissions de canal vocal." }, { title: "Rejoignez un canal vocal", description: "HypeBot détecte quand vous êtes dans un canal vocal et rejoint automatiquement (ou sur commande)." }, { title: "Commencez à parler", description: "Parlez naturellement. HypeBot écoute via STT, traite avec l'IA et répond avec Murf Falcon TTS en ~130ms." }, { title: "Connectez GitHub", description: "Optionnel : Liez vos repos. HypeBot annonce les commits, PRs et résultats CI en direct par la voix." }] },
  demo: { label: "Démo en direct", title: "Parlez à ", titleHighlight: "HypeBot", subtitle: "Cliquez sur le micro, dites quelque chose et écoutez votre collègue IA répondre avec la voix ultra-faible latence de Murf Falcon.", personas: { hype: "🔥 Hype Man", coach: "🎯 Coach Strict", roast: "💀 Critique de code" }, voiceLabel: "🦅 Voix Murf Falcon", loadingVoices: "Chargement des voix...", selectVoice: "Sélectionner une voix Falcon", noVoices: "Aucune voix Falcon trouvée. Vérifiez votre clé API.", clickMic: "Cliquez sur le micro et parlez", listening: "Écoute en cours... cliquez pour arrêter", processing: "Traitement avec Falcon AI...", speaking: "HypeBot parle via Murf Falcon...", youSaid: "Vous avez dit :", loadingFalcon: "Chargement des voix Falcon..." },
  footer: { builtWith: "Construit avec Murf Falcon • Hackathon 2026" },
  languageSwitcher: { search: "Rechercher des langues...", noResults: "Aucune langue trouvée" },
};
