import { Translations } from "../types";
export const hi: Translations = {
  nav: { features: "विशेषताएं", liveDemo: "लाइव डेमो", howItWorks: "कैसे काम करता है", github: "GitHub", tryDemo: "डेमो आज़माएं" },
  hero: { badge: "Murf Falcon द्वारा संचालित — ~130ms विलंबता", titleLine1: "आपका AI", titleLine2: "हाइप मैन", titleLine3: "Discord पर", subtitle: "एक Discord बॉट जो आपके वॉइस चैनल में लाइव कमेंटेटर, प्रोडक्टिविटी कोच या कोड रिव्यूअर के रूप में शामिल होता है — सब रियल-टाइम वॉइस में।", ctaTryDemo: "लाइव डेमो आज़माएं", ctaAddDiscord: "Discord में जोड़ें", botName: "HypeBot", botStatus: "● वॉइस में ऑनलाइन", botQuote: '"अरे! वो आखिरी कमिट तो आग थी 🔥 साफ रिफैक्टरिंग, सही टाइप्स, जीरो वार्निंग। आज तू अलग है!"' },
  features: { label: "विशेषताएं", title: "", titleHighlight: "रियल-टाइम", subtitle: "Discord पर वास्तव में बात करने वाले AI सहकर्मी के लिए आपको जो कुछ भी चाहिए।", items: [{ title: "रियल-टाइम वॉइस", description: "आपके Discord वॉइस चैनल में शामिल होता है और Murf Falcon के अल्ट्रा-लो लेटेंसी TTS से तुरंत जवाब देता है।" }, { title: "~130ms प्रतिक्रिया", description: "Falcon का तेज़ इन्फ़ेरेंस प्राकृतिक, बिना रुकावट बातचीत प्रवाह सुनिश्चित करता है।" }, { title: "GitHub रोस्ट्स", description: "वेबहुक कनेक्ट करें और अपने कमिट्स की तारीफ़ या आलोचना करने वाली लाइव वॉइस सूचनाएं प्राप्त करें।" }, { title: "कई व्यक्तित्व", description: "हाइप मैन, सख्त कोच, कोड रिव्यूअर के बीच स्विच करें या अपना खुद का व्यक्तित्व बनाएं।" }, { title: "स्पीच-टू-टेक्स्ट", description: "रियल-टाइम में आपकी आवाज़ सुनता है, संदर्भ समझता है और बुद्धिमानी से जवाब देता है।" }, { title: "प्रोडक्टिविटी मोड", description: "पोमोडोरो टाइमर घोषणाएं, स्टैंडअप रिमाइंडर और फोकस सेशन कोचिंग।" }] },
  howItWorks: { label: "कैसे काम करता है", title: "कुछ ही ", titleHighlight: "मिनटों में तैयार", steps: [{ title: "HypeBot को आमंत्रित करें", description: "एक क्लिक से HypeBot को अपने Discord सर्वर में जोड़ें। वॉइस चैनल अनुमतियां दें।" }, { title: "वॉइस चैनल में शामिल हों", description: "HypeBot आपको वॉइस चैनल में पहचानता है और स्वचालित रूप से शामिल होता है।" }, { title: "बात करना शुरू करें", description: "स्वाभाविक रूप से बोलें। HypeBot STT से सुनता है, AI से प्रोसेस करता है और ~130ms में Murf Falcon TTS से जवाब देता है।" }, { title: "GitHub कनेक्ट करें", description: "वैकल्पिक: अपने रेपो लिंक करें। HypeBot कमिट, PR और CI परिणाम लाइव वॉइस में घोषित करता है।" }] },
  demo: { label: "लाइव डेमो", title: "", titleHighlight: "HypeBot से बात करें", subtitle: "माइक पर क्लिक करें, कुछ कहें और अपने AI सहकर्मी को Murf Falcon की अल्ट्रा-लो लेटेंसी वॉइस से जवाब देते सुनें।", personas: { hype: "🔥 हाइप मैन", coach: "🎯 सख्त कोच", roast: "💀 कोड रोस्टर" }, voiceLabel: "🦅 Murf Falcon वॉइस", loadingVoices: "वॉइस लोड हो रही हैं...", selectVoice: "Falcon वॉइस चुनें", noVoices: "कोई Falcon वॉइस नहीं मिली। API कुंजी जांचें।", clickMic: "माइक पर क्लिक करें और बोलें", listening: "सुन रहा है... रोकने के लिए क्लिक करें", processing: "Falcon AI से प्रोसेसिंग...", speaking: "HypeBot Murf Falcon से बोल रहा है...", youSaid: "आपने कहा:", loadingFalcon: "Falcon वॉइस लोड हो रही हैं..." },
  footer: { builtWith: "Murf Falcon से निर्मित • Hackathon 2026" },
  languageSwitcher: { search: "भाषाएं खोजें...", noResults: "कोई भाषा नहीं मिली" },
};
