import { Translations } from "../types";
export const ja: Translations = {
  nav: { features: "機能", liveDemo: "ライブデモ", howItWorks: "使い方", github: "GitHub", tryDemo: "デモを試す" },
  hero: { badge: "Murf Falcon搭載 — ~130msの遅延", titleLine1: "あなたのAI", titleLine2: "ハイプマン", titleLine3: "Discord上の", subtitle: "ライブコメンテーター、生産性コーチ、辛口コードレビュアーとしてボイスチャンネルに参加するDiscordボット — すべてリアルタイム音声。", ctaTryDemo: "ライブデモを試す", ctaAddDiscord: "Discordに追加", botName: "HypeBot", botStatus: "● ボイスでオンライン", botQuote: '"おい！最後のコミットは最高だった 🔥 きれいなリファクタリング、正しい型、警告ゼロ。今日は一味違うな！"' },
  features: { label: "機能", title: "", titleHighlight: "リアルタイム", subtitle: "Discordで実際に話しかけてくれるAI同僚に必要なすべて。", items: [{ title: "リアルタイム音声", description: "Discordのボイスチャンネルに参加し、Murf Falconの超低遅延TTSで即座に応答。" }, { title: "~130msの応答", description: "Falconの超高速推論で自然で途切れのない会話フロー。" }, { title: "GitHubロースト", description: "Webhookを接続して、コミットを褒めたりロースとするライブ音声アナウンスを取得。" }, { title: "複数のペルソナ", description: "ハイプマン、厳格コーチ、コードレビュアーを切り替えるか、独自のパーソナリティを作成。" }, { title: "音声認識", description: "リアルタイムで音声を聞き、コンテキストを理解し、インテリジェントに応答。" }, { title: "生産性モード", description: "ポモドーロタイマーアナウンス、スタンドアップリマインダー、フォーカスセッションコーチング。" }] },
  howItWorks: { label: "使い方", title: "数", titleHighlight: "分で稼働", steps: [{ title: "HypeBotを招待", description: "ワンクリックでHypeBotをDiscordサーバーに追加。ボイスチャンネルの権限を付与。" }, { title: "ボイスチャンネルに参加", description: "HypeBotがボイスチャンネルにいることを検知し、自動的に参加（またはコマンドで）。" }, { title: "話し始める", description: "自然に話してください。HypeBotがSTTで聞き、AIで処理し、~130msでMurf Falcon TTSで応答。" }, { title: "GitHubを接続", description: "オプション：リポジトリをリンク。HypeBotがコミット、PR、CI結果を音声でライブアナウンス。" }] },
  demo: { label: "ライブデモ", title: "", titleHighlight: "HypeBotと話す", subtitle: "マイクをクリックして何か言うと、Murf Falconの超低遅延音声でAI同僚が応答します。", personas: { hype: "🔥 ハイプマン", coach: "🎯 厳格コーチ", roast: "💀 コードロースター" }, voiceLabel: "🦅 Murf Falcon ボイス", loadingVoices: "ボイス読み込み中...", selectVoice: "Falconボイスを選択", noVoices: "Falconボイスが見つかりません。APIキーを確認してください。", clickMic: "マイクをクリックして話す", listening: "聞いています...クリックで停止", processing: "Falcon AIで処理中...", speaking: "HypeBotがMurf Falconで話しています...", youSaid: "あなたの発言:", loadingFalcon: "Falconボイス読み込み中..." },
  footer: { builtWith: "Murf Falcon で構築 • Hackathon 2026" },
  languageSwitcher: { search: "言語を検索...", noResults: "言語が見つかりません" },
};
