import { Translations } from "../types";
export const ko: Translations = {
  nav: { features: "기능", liveDemo: "라이브 데모", howItWorks: "사용 방법", github: "GitHub", tryDemo: "데모 체험" },
  hero: { badge: "Murf Falcon 구동 — ~130ms 지연시간", titleLine1: "당신의 AI", titleLine2: "하이프맨", titleLine3: "Discord에서", subtitle: "음성 채널에 참여하여 라이브 해설자, 생산성 코치 또는 냉정한 코드 리뷰어 역할을 하는 Discord 봇 — 모두 실시간 음성.", ctaTryDemo: "라이브 데모 체험", ctaAddDiscord: "Discord에 추가", botName: "HypeBot", botStatus: "● 음성에서 온라인", botQuote: '"야! 마지막 커밋 완전 불이야 🔥 깔끔한 리팩토링, 정확한 타입, 경고 제로. 오늘 너 다르다!"' },
  features: { label: "기능", title: "", titleHighlight: "실시간", subtitle: "Discord에서 실제로 대화하는 AI 동료에게 필요한 모든 것.", items: [{ title: "실시간 음성", description: "Discord 음성 채널에 참여하고 Murf Falcon의 초저지연 TTS로 즉시 응답." }, { title: "~130ms 응답", description: "Falcon의 초고속 추론으로 자연스럽고 끊김 없는 대화 흐름." }, { title: "GitHub 로스트", description: "웹훅을 연결하고 커밋을 칭찬하거나 로스트하는 라이브 음성 공지를 받으세요." }, { title: "다중 페르소나", description: "하이프맨, 엄격한 코치, 코드 리뷰어 간 전환하거나 자신만의 개성을 만드세요." }, { title: "음성 인식", description: "실시간으로 음성을 듣고 맥락을 이해하며 지능적으로 응답." }, { title: "생산성 모드", description: "포모도로 타이머 공지, 스탠드업 알림 및 집중 세션 코칭." }] },
  howItWorks: { label: "사용 방법", title: "몇 ", titleHighlight: "분 만에 시작", steps: [{ title: "HypeBot 초대", description: "한 번의 클릭으로 Discord 서버에 HypeBot을 추가하세요. 음성 채널 권한을 부여하세요." }, { title: "음성 채널 참여", description: "HypeBot이 음성 채널에 있는 것을 감지하고 자동으로 참여 (또는 명령으로)." }, { title: "대화 시작", description: "자연스럽게 말하세요. HypeBot이 STT로 듣고 AI로 처리하며 ~130ms 내에 Murf Falcon TTS로 응답." }, { title: "GitHub 연결", description: "선택: 리포를 연결하세요. HypeBot이 커밋, PR, CI 결과를 음성으로 라이브 공지." }] },
  demo: { label: "라이브 데모", title: "", titleHighlight: "HypeBot과 대화", subtitle: "마이크를 클릭하고 말하면 Murf Falcon의 초저지연 음성으로 AI 동료가 응답합니다.", personas: { hype: "🔥 하이프맨", coach: "🎯 엄격한 코치", roast: "💀 코드 로스터" }, voiceLabel: "🦅 Murf Falcon 음성", loadingVoices: "음성 로딩 중...", selectVoice: "Falcon 음성 선택", noVoices: "Falcon 음성을 찾을 수 없습니다. API 키를 확인하세요.", clickMic: "마이크를 클릭하고 말하세요", listening: "듣고 있습니다... 클릭하여 중지", processing: "Falcon AI로 처리 중...", speaking: "HypeBot이 Murf Falcon으로 말하고 있습니다...", youSaid: "당신이 말한 것:", loadingFalcon: "Falcon 음성 로딩 중..." },
  footer: { builtWith: "Murf Falcon으로 제작 • Hackathon 2026" },
  languageSwitcher: { search: "언어 검색...", noResults: "언어를 찾을 수 없습니다" },
};
