import { Translations } from "../types";
export const pt: Translations = {
  nav: { features: "Recursos", liveDemo: "Demo ao vivo", howItWorks: "Como funciona", github: "GitHub", tryDemo: "Testar demo" },
  hero: { badge: "Alimentado por Murf Falcon — ~130ms de latência", titleLine1: "Sua IA", titleLine2: "Hype Man", titleLine3: "no Discord", subtitle: "Um bot do Discord que entra no seu canal de voz como comentarista ao vivo, coach de produtividade ou revisor de código implacável — tudo em voz em tempo real.", ctaTryDemo: "Testar demo ao vivo", ctaAddDiscord: "Adicionar ao Discord", botName: "HypeBot", botStatus: "● Online na voz", botQuote: '"Eai! Esse último commit foi FOGO 🔥 Refatoração limpa, tipos corretos, zero avisos. Você está diferente hoje!"' },
  features: { label: "Recursos", title: "Feito para ", titleHighlight: "tempo real", subtitle: "Tudo que você precisa para um colega de IA que realmente fala com você no Discord.", items: [{ title: "Voz em tempo real", description: "Entra no seu canal de voz do Discord e responde instantaneamente usando o TTS de ultra baixa latência do Murf Falcon." }, { title: "~130ms de resposta", description: "A inferência ultrarrápida do Falcon permite um fluxo de conversa natural e ininterrupto." }, { title: "Roasts do GitHub", description: "Conecte webhooks e receba anúncios de voz ao vivo elogiando ou criticando seus commits." }, { title: "Múltiplas personas", description: "Alterne entre Hype Man, Coach Rígido, Revisor de Código ou crie sua própria personalidade." }, { title: "Fala para texto", description: "Ouve sua voz em tempo real, entende o contexto e responde inteligentemente." }, { title: "Modos de produtividade", description: "Anúncios de timer Pomodoro, lembretes de standup e coaching de sessões de foco." }] },
  howItWorks: { label: "Como funciona", title: "Pronto e funcionando em ", titleHighlight: "minutos", steps: [{ title: "Convide o HypeBot", description: "Adicione o HypeBot ao seu servidor Discord com um clique. Conceda permissões de canal de voz." }, { title: "Entre em um canal de voz", description: "O HypeBot detecta quando você está em um canal de voz e entra automaticamente (ou por comando)." }, { title: "Comece a falar", description: "Fale naturalmente. O HypeBot ouve via STT, processa com IA e responde com Murf Falcon TTS em ~130ms." }, { title: "Conecte o GitHub", description: "Opcional: Vincule seus repos. O HypeBot anuncia commits, PRs e resultados de CI ao vivo por voz." }] },
  demo: { label: "Demo ao vivo", title: "Fale com o ", titleHighlight: "HypeBot", subtitle: "Clique no microfone, diga algo e ouça seu colega de IA responder com a voz de ultra baixa latência do Murf Falcon.", personas: { hype: "🔥 Hype Man", coach: "🎯 Coach Rígido", roast: "💀 Crítico de código" }, voiceLabel: "🦅 Vozes Murf Falcon", loadingVoices: "Carregando vozes...", selectVoice: "Selecionar voz Falcon", noVoices: "Nenhuma voz Falcon encontrada. Verifique sua chave API.", clickMic: "Clique no microfone e fale", listening: "Ouvindo... clique para parar", processing: "Processando com Falcon AI...", speaking: "HypeBot está falando via Murf Falcon...", youSaid: "Você disse:", loadingFalcon: "Carregando vozes Falcon..." },
  footer: { builtWith: "Construído com Murf Falcon • Hackathon 2026" },
  languageSwitcher: { search: "Pesquisar idiomas...", noResults: "Nenhum idioma encontrado" },
};
